/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author User
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        setTitle("Dashboard");
        setSize(1024, 683);
    }
    
    int[] TRABAJADORES = new int [6];
    
    public void GuardarTotalEmpleados(){
        //int NumeroTrabajadoresDisenadorEscenarios = (int) DisenadorEscenarios.getValue();
        //JOptionPane.showMessageDialog(rootPane, "Tienes: "+ NumeroTrabajadoresDisenadorEscenarios);
        
    
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CartoonNetworkBoton = new javax.swing.JButton();
        DisneyChanelBoton = new javax.swing.JButton();
        CorrerBoton = new javax.swing.JButton();
        TOTAL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        CartoonNetworkBoton.setText("Cartoon Network");
        CartoonNetworkBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartoonNetworkBotonActionPerformed(evt);
            }
        });
        getContentPane().add(CartoonNetworkBoton);
        CartoonNetworkBoton.setBounds(10, 10, 150, 23);

        DisneyChanelBoton.setText("Disney Channel");
        DisneyChanelBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisneyChanelBotonActionPerformed(evt);
            }
        });
        getContentPane().add(DisneyChanelBoton);
        DisneyChanelBoton.setBounds(790, 20, 180, 23);

        CorrerBoton.setText("Correr");
        CorrerBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrerBotonActionPerformed(evt);
            }
        });
        getContentPane().add(CorrerBoton);
        CorrerBoton.setBounds(390, 490, 130, 23);
        getContentPane().add(TOTAL);
        TOTAL.setBounds(550, 260, 120, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CartoonNetworkBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartoonNetworkBotonActionPerformed
        // TODO add your handling code here:
        CartoonNetwork CN = new CartoonNetwork();
        dispose();
        CN.setLocationRelativeTo(null);
        CN.setVisible(true);
        
    }//GEN-LAST:event_CartoonNetworkBotonActionPerformed

    private void CorrerBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrerBotonActionPerformed
        // TODO add your handling code here:
        
        
        
    
    }//GEN-LAST:event_CorrerBotonActionPerformed

    private void DisneyChanelBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisneyChanelBotonActionPerformed
        // TODO add your handling code here:
        DisneyChannel DC = new DisneyChannel();
        dispose();
        DC.setLocationRelativeTo(null);
        DC.setVisible(true);
    }//GEN-LAST:event_DisneyChanelBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CartoonNetworkBoton;
    private javax.swing.JButton CorrerBoton;
    private javax.swing.JButton DisneyChanelBoton;
    private javax.swing.JLabel TOTAL;
    // End of variables declaration//GEN-END:variables
}
