/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class DisneyChannel extends javax.swing.JFrame {

    /**
     * Creates new form DisneyChannel
     */
    public DisneyChannel() {
        initComponents();
        initComponents();
        setTitle("Disney Channel");
        setSize(1024, 683);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DiseñadorEscenariosDisney = new javax.swing.JSpinner();
        AnimadorPersonajesDisney = new javax.swing.JSpinner();
        DirectorDisney = new javax.swing.JSpinner();
        ActoresDoblajeDisney = new javax.swing.JSpinner();
        GuionistaPlotTwistDisney = new javax.swing.JSpinner();
        GuionistasDisney = new javax.swing.JSpinner();
        ProjectManagerDisney = new javax.swing.JSpinner();
        EnsambladoresDisney = new javax.swing.JSpinner();
        Actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(6, 14, 110, 23);

        jLabel2.setText("Animador de personajes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 140, 160, 16);

        jLabel8.setText("Empleados Disney:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(39, 68, 99, 16);

        jLabel11.setText("Diseñador de Escenarios:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 110, 130, 16);

        jLabel9.setText("Guionistas");
        jLabel9.setToolTipText("");
        jLabel9.setName(""); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 320, 160, 20);

        jLabel3.setText("Actores de doblaje");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 170, 130, 16);

        jLabel4.setText("Guionista de PlotTwist");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 200, 160, 16);

        jLabel5.setText("Ensambladores");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 230, 120, 16);

        jLabel6.setText("Project Manager");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 260, 110, 16);

        jLabel7.setText("Director");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 290, 120, 16);

        DiseñadorEscenariosDisney.setValue(1);
        DiseñadorEscenariosDisney.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DiseñadorEscenariosDisneyStateChanged(evt);
            }
        });
        getContentPane().add(DiseñadorEscenariosDisney);
        DiseñadorEscenariosDisney.setBounds(170, 110, 82, 22);

        AnimadorPersonajesDisney.setValue(1);
        AnimadorPersonajesDisney.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AnimadorPersonajesDisneyStateChanged(evt);
            }
        });
        getContentPane().add(AnimadorPersonajesDisney);
        AnimadorPersonajesDisney.setBounds(170, 140, 82, 22);

        DirectorDisney.setValue(1);
        getContentPane().add(DirectorDisney);
        DirectorDisney.setBounds(170, 290, 82, 22);

        ActoresDoblajeDisney.setValue(1);
        getContentPane().add(ActoresDoblajeDisney);
        ActoresDoblajeDisney.setBounds(170, 170, 82, 22);

        GuionistaPlotTwistDisney.setValue(1);
        getContentPane().add(GuionistaPlotTwistDisney);
        GuionistaPlotTwistDisney.setBounds(170, 200, 82, 22);

        GuionistasDisney.setValue(1);
        getContentPane().add(GuionistasDisney);
        GuionistasDisney.setBounds(170, 320, 82, 22);

        ProjectManagerDisney.setValue(1);
        getContentPane().add(ProjectManagerDisney);
        ProjectManagerDisney.setBounds(170, 260, 82, 22);

        EnsambladoresDisney.setValue(1);
        getContentPane().add(EnsambladoresDisney);
        EnsambladoresDisney.setBounds(170, 230, 82, 22);

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Actualizar);
        Actualizar.setBounds(310, 370, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DashBoard DB = new DashBoard();
        dispose();
        DB.setLocationRelativeTo(null);
        DB.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
        int NumeroTrabajadoresDisenadorEscenarios = (int) DiseñadorEscenariosDisney.getValue();
        
        int NumeroTrabajadoresAnimadorPersonajes = (int) AnimadorPersonajesDisney.getValue();
        
        int NumeroActoresDoblaje = (int) ActoresDoblajeDisney.getValue();
        
        int NumeroGuionistaPlotTwist = (int) GuionistaPlotTwistDisney.getValue();
        
        int NumeroEnsambladores = (int) EnsambladoresDisney.getValue();
        
        int NumeroProjectManager = (int) ProjectManagerDisney.getValue();
        
        int NumeroDirector1 = (int) DirectorDisney.getValue();
        
        int NumeroGuionistas = (int) GuionistasDisney.getValue();
        
        int[] valores = {
            NumeroTrabajadoresDisenadorEscenarios,
            NumeroTrabajadoresAnimadorPersonajes,
            NumeroActoresDoblaje,
            NumeroGuionistaPlotTwist,
            NumeroEnsambladores,
            NumeroProjectManager,
            NumeroDirector1,
            NumeroGuionistas
        };

        // Sumar los valores en el array usando un bucle
        int suma = 0;
        for (int valor : valores) {
            suma += valor;
        }
        
        //Ver el total de la suma:
        //JOptionPane.showMessageDialog(rootPane, "La suma total es: " + suma);
        
        if (suma > 13){
            JOptionPane.showMessageDialog(rootPane, "No puden haber mas de 13 trabajadores");
        }else{
            JOptionPane.showMessageDialog(rootPane, "En marcha !");
        }
    }//GEN-LAST:event_ActualizarActionPerformed

    private void DiseñadorEscenariosDisneyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DiseñadorEscenariosDisneyStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DiseñadorEscenariosDisneyStateChanged

    private void AnimadorPersonajesDisneyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AnimadorPersonajesDisneyStateChanged
        // TODO add your handling code here:
        int valorActual = (int) AnimadorPersonajesDisney.getValue();
        if (valorActual == 0){
            JOptionPane.showMessageDialog(rootPane, "Cada estudio de animación debe contar en todo momento con un " + "trabajador de cada tipo como mínimo ");
            AnimadorPersonajesDisney.setValue(1);
        }
    }//GEN-LAST:event_AnimadorPersonajesDisneyStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisneyChannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisneyChannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisneyChannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisneyChannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisneyChannel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ActoresDoblajeDisney;
    private javax.swing.JButton Actualizar;
    private javax.swing.JSpinner AnimadorPersonajesDisney;
    private javax.swing.JSpinner DirectorDisney;
    private javax.swing.JSpinner DiseñadorEscenariosDisney;
    private javax.swing.JSpinner EnsambladoresDisney;
    private javax.swing.JSpinner GuionistaPlotTwistDisney;
    private javax.swing.JSpinner GuionistasDisney;
    private javax.swing.JSpinner ProjectManagerDisney;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
